### ISSUE TITLE
The new irodsFs command line options don't allow space between -o and option name

### ISSUE THREAD

**Issue by tedgin** [cyverse/cyverse-irods#2]
The new irodsFs command line options don't allow space between the `-o` and the option name.  

This works.

```
irodsFs -o allow_other -oconnreuse -ometadatacachetimeout 3600 -opreloadblocks 5 /mnt
```

This doesn't. 

```
irodsFs -o allow_other -o connreuse -o metadatacachetimeout 3600 -o preloadblocks 5 /mnt
```

It actually core dumps.

Please either have the command fail with an error message or accept space between the `-o` and the option name in all cases.

**Comment by iychoi** [comment]
Fixed at commit 58500d2a4d85ed61da7cce23148865f1449c0752
